### ISSUE TITLE
How to set the RosService parameters?

### ISSUE THREAD

**Issue by pkr97** [orsalmon/KUKA_KR5_manipulator_gazebo#2]
I'm able to get the things ready but still facing some issue in sending the comand to controllers because I'm unable to use the following command.
"rosservice call /move_arm"

How can I set the parameters for these arguments in terminal?
std_msgs/Float64[3] desired_xyz
std_msgs/Float64    duration

I used " rosservice call /move_arm "data: 0.5, 0.5, 0.5" "data: 0.6" "
but getting error...

thanks...

**Comment by pkr97** [comment]
Found an answer.

The fomat is as follows

rosservice call /move_arm "desired_xyz:
- data: 0.2                                          
- data: 0.2
- data: 0.7
duration:
  data: 6.0"

**Comment by enigma0503** [comment]
Can you please write down the command in a line as it needs to be written in the terminal?

**Comment by enigma0503** [comment]
> Found an answer.
> 
> The fomat is as follows
> 
> rosservice call /move_arm "desired_xyz:
> 
> * data: 0.2
> * data: 0.2
> * data: 0.7
>   duration:
>   data: 6.0"

Can you please write down the command in a line as it needs to be written in the terminal?
